name: cara_ou_coroa_gigachad_edition
description: "Aplicativo de cara ou coroa, mas com a versão Gigachad da moeda de 1 Real."
publish_to: 'none'
version: 1.0.0 # major.minor.patch+build (Mudanças críticas que quebram a build anterior . Novas features que não quebram nada anterior . Pequenas correções e melhorias + Número da publicação)

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_3d_controller: ^2.2.0
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/3d_models/
